name: azure_notificationhubs_flutter
description: Flutter plugin for Azure Notification Hubs
version: 0.0.1
homepage: https://github.com/rswiftoffice/azure-notificationhubs-flutter
repository: https://github.com/rswiftoffice/azure-notificationhubs-flutter
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.swiftoffice.azure_notificationhubs_flutter
    pluginClass: AzureNotificationhubsFlutterPlugin